// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtHvcCKWyRwMLaN3lrW00ql6e1GcuxFSk',
    appId: '1:28896068278:web:d0096f4bb131b6aefd5c17',
    messagingSenderId: '28896068278',
    projectId: 'checkiin',
    authDomain: 'checkiin.firebaseapp.com',
    storageBucket: 'checkiin.appspot.com',
    measurementId: 'G-YYCPS7RV4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwKJhKyuMuh2DV1thg6m2_x5V_RD_VK8E',
    appId: '1:28896068278:android:94b9bdec8a43a219fd5c17',
    messagingSenderId: '28896068278',
    projectId: 'checkiin',
    storageBucket: 'checkiin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqjTvyhn3xAR9vg2QnmonRyGmTG-rBVmE',
    appId: '1:28896068278:ios:63d02ef5c17b8c0afd5c17',
    messagingSenderId: '28896068278',
    projectId: 'checkiin',
    storageBucket: 'checkiin.appspot.com',
    iosBundleId: 'com.example.checkiin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqjTvyhn3xAR9vg2QnmonRyGmTG-rBVmE',
    appId: '1:28896068278:ios:7ba692b618f4a208fd5c17',
    messagingSenderId: '28896068278',
    projectId: 'checkiin',
    storageBucket: 'checkiin.appspot.com',
    iosBundleId: 'com.example.checkiin.RunnerTests',
  );
}
